### ISSUE TITLE
Uncaught TypeError: Cannot set property 'uiBackCompat' of undefined(…)

### ISSUE THREAD

**Issue by kzpromo** [vidyamantra/moodle-local_vmchat#11]
i have recived error massage in console
**Uncaught TypeError: Cannot set property 'uiBackCompat' of undefined(…)**
http://e.neu.kz/local/vmchat/index.js in 28 line

how can i fix this error?

**Comment by pinky28** [comment]
You are using older version of Vmchat, use latest version for better result. If your Moodle is compatible with that version only then hide this line in code and it will work for you.

**Comment by kzpromo** [comment]
@pinky28 if i will hide this line, i will recive new errors
please help me to solve this problem
we cant update whole vmchat, becouse our version of moodle does not allow to do that

**Comment by pinky28** [comment]
Please tell us  your Moodle and Vmchat version.

**Comment by kzpromo** [comment]
@pinky28 
Moodle 2.7.14 (Build: 20160509)
Vmchat version 2015091100 release 1.2.4 (Build: 2015091100)

**Comment by pinky28** [comment]
We are unable to reproduce this error at our end with given version. If possible, please share you Url and login credential at support@vidyamantra.com for troubleshooting.

**Comment by kzpromo** [comment]
@pinky28 I've posted
