### ISSUE TITLE
Ajax request failed

### ISSUE THREAD

**Issue by schalkvn** [vidyamantra/moodle-local_vmchat#14]
I get the following error when attempting to submit form for Get Key - see image, attached
![screen shot 2017-08-28 at 10 00 07 pm](https://user-images.githubusercontent.com/30025756/29802872-e60101fa-8c3d-11e7-8cd9-b823cbad54cf.png)

Please advise.

**Comment by pinky28** [comment]
This was temporary error which has been fixed now.
