### ISSUE TITLE
VM Chat not appear Adaptable Theme in Moodle 3.1.1

### ISSUE THREAD

**Issue by raymarq** [vidyamantra/moodle-local_vmchat#9]
Not the CHAT appears in moodle 3.1.1
Use the Adaptable theme

**Comment by bogatisuman** [comment]
Please get the fixed version from https://github.com/vidyamantra/moodle-local_vmchat. The chat will appear on this version.

**Comment by bogatisuman** [comment]
Please get the fixed version from https://github.com/vidyamantra/moodle-local_vmchat.  The chat will appear with this version on Adaptable theme.
